name: Update Clones

on:
  push:
    branches:
      - react-bricks

jobs:
  update-clones:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push updates to cloned repositories
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/pablo-lujan/web-builder.git"
          source_branch: "react-bricks"
          destination_branch: "react-bricks"
          github_token: ${{ secrets.PAT }}
